[package]
name = "handlers"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
oxid-core = { workspace = true }
auth = { workspace = true }
common = { workspace = true }
server = { workspace = true }
args = { workspace = true }

axum = { workspace = true }
http = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
